import mdx from "@astrojs/mdx";
import react from "@astrojs/react";
import sitemap from "@astrojs/sitemap";
import tailwind from "@astrojs/tailwind";
import vercel from "@astrojs/vercel/serverless";
import icon from "astro-icon";
import { defineConfig } from "astro/config";
import simpleStackForm from "simple-stack-form";
import db from "@astrojs/db";
import partytown from "@astrojs/partytown"

//// https://astro.build/config
export default defineConfig({
  site: "https://usagepricing.com",
  integrations: [
    mdx({
      syntaxHighlight: "shiki",
      shikiConfig: {
        theme: "github-dark-dimmed",
      },
      gfm: true,
    }),
    icon(),
    sitemap({
      filter: (page) => {
        // Exclude draft pages from the sitemap
        // This assumes your content collections have a 'draft' property in their frontmatter
        // You might need to adjust this logic based on how your drafts are identified
        if (page.includes('/blog/') || page.includes('/docs/') || page.includes('/guides/') || page.includes('/explained/') || page.includes('/releases/')) {
          // For content collection pages, we need to check their frontmatter
          // This requires fetching the collection entry, which is not directly possible here.
          // A common pattern is to filter during collection fetching or use a custom sitemap generation.
          // For now, we'll assume that if a page is a draft, it won't be generated by getStaticPaths
          // if getStaticPaths already filters drafts.
          return true; // Allow all content collection pages for now, rely on getStaticPaths filtering
        }
        return true;
      },
    }),
    react(),
    tailwind({
      applyBaseStyles: false,
    }),
    simpleStackForm(),
    partytown({ config: { forward: ['dataLayer.push'] } }),
    
    db( {
      adapter: "turso",
      dbUrl: import.meta.env.DB_URL,
      authToken: import.meta.env.DB_AUTH_TOKEN,
    }),
  ],
  output: "hybrid",
  adapter: vercel({
    analytics: true,
    functionPerRoute: true, // optional
    runtime: "nodejs",
  }),
});
